# Server settings
server:
    port: 8080
    address: localhost

# DATASOURCE
jdbc:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: book
    serverName: 127.0.0.1
    username: root
    password: 123456
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    resources:
         static-locations: classpath:/static/
    mvc:
      view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

# MyBatis
mybatis:
    typeAliasesPackage: com.online.cms.**.domain
    mapperLocations: classpath:/com/online/cms/**/dao/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG